import type {Vec2,Project} from '../src/domain/model';
import type {Draft,MeasuredScale,NetworkInput} from './project-tools';
import {originalPointerToDraft} from './project-tools';
export type DrawingTool='a'|'b'|'cabinet'|'wan'|'dimension-from'|'dimension-to'|null;
export function DrawingReview({url,original,draft,calibration,config,network,tool,onPoint,onError}:{url:string;original?:{width:number;height:number}|null;draft:Draft;calibration:MeasuredScale;config:NetworkInput;network?:Project;tool:DrawingTool;onPoint:(p:Vec2)=>void;onError:(message:string)=>void}){
 const matches=!!original&&original.width===draft.width&&original.height===draft.height;
 const floor=network?.floors[0],c=floor?.calibration;
 const inactiveCameras=new Set(network?.settings.monitoring?[]:floor?.devices.filter(d=>d.kind==='camera').map(d=>d.id));
 const pixel=(p:Vec2)=>{const s=c?.metersPerPixel??1,angle=c?.angleRad??0,origin=c?.originPx??{x:0,y:0};return {x:origin.x+(p.x*Math.cos(angle)+p.y*Math.sin(angle))/s,y:origin.y+(-p.x*Math.sin(angle)+p.y*Math.cos(angle))/s}};
 const points=(ps:Vec2[],convert=false)=>ps.map(p=>{const v=convert?pixel(p):p;return `${v.x},${v.y}`}).join(' ');
 return <section id="team-review" className="drawing-review"><h3>在原图上确认与布点</h3>{!matches&&<p role="alert">原图与草稿坐标框不一致或原图尚未保存。禁止叠加、点选和生成；请保留草稿后重新取得匹配原图坐标的识别结果。</p>}{matches&&url&&<svg role="img" aria-label="原图校正与组网点位" viewBox={`0 0 ${draft.width} ${draft.height}`} onClick={e=>{if(!tool)return;try{const matrix=e.currentTarget.getScreenCTM();if(!matrix)throw Error('原图显示坐标不可用');const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());onPoint(originalPointerToDraft({clientX:point.x,clientY:point.y},{left:0,top:0,width:draft.width,height:draft.height},original!,draft))}catch(error){onError(error instanceof Error?error.message:'无法选择端点')}}} style={{cursor:tool?'crosshair':'default'}}><image href={url} width={draft.width} height={draft.height}/>{draft.rooms.map((r,i)=><g key={i}><polygon className="candidate-room" points={points(r.polygon)}/><text x={r.polygon[0]?.x} y={r.polygon[0]?.y} fontSize={draft.width/70}>{r.name}</text></g>)}{draft.walls.map((w,i)=><line key={`wall${i}`} className="candidate-wall" x1={w.from.x} y1={w.from.y} x2={w.to.x} y2={w.to.y}/>)}{draft.openings?.map((o,i)=><line key={`opening${i}`} className="candidate-opening" x1={o.from.x} y1={o.from.y} x2={o.to.x} y2={o.to.y}/>)}{draft.dimensions?.map((d,i)=><g key={`dim${i}`}><line className="candidate-dimension" x1={d.from.x} y1={d.from.y} x2={d.to.x} y2={d.to.y}/><text x={d.from.x} y={d.from.y} fontSize={draft.width/80}>{d.value} {d.unit}</text></g>)}<line className="scale-reference" x1={calibration.a.x} y1={calibration.a.y} x2={calibration.b.x} y2={calibration.b.y}/>{(['cabinet','wan'] as const).map(kind=>config[kind]&&<g key={kind}><circle cx={config[kind]!.x} cy={config[kind]!.y} r={draft.width/100}/><text x={config[kind]!.x} y={config[kind]!.y} fontSize={draft.width/65}>{kind==='cabinet'?'机柜':'宽带入口'}</text></g>)}{floor?.cables.filter(line=>!inactiveCameras.has(line.fromId)&&!inactiveCameras.has(line.toId)).map(line=><polyline key={line.id} className="network-cable" fill="none" points={points(line.pointsM,true)}/>)}{floor?.devices.filter(d=>!['cabinet','wan'].includes(d.kind)&&(d.kind!=='camera'||network?.settings.monitoring)).map(d=>{const p=pixel(d.positionM);return <g key={d.id} data-device-kind={d.kind}><circle cx={p.x} cy={p.y} r={draft.width/100}/><text x={p.x} y={p.y} fontSize={draft.width/65}>{d.label}</text></g>})}</svg>}<p>蓝色：区域候选；红色：实体墙；绿色：门洞；紫色：尺寸。AP／有线点位与线路按方案尺度逆变换回原图。监控尚未接入此网页流程。</p></section>
}
