import {DrawingReview,type DrawingTool} from './DrawingReview';
import {deriveProject} from '../src/quote/derive';
import {catalog} from '../src/catalog/models';
import {parseProject} from '../src/project/repository';
import {DimensionsPanel} from './DimensionsPanel';
import {useEffect,useState,useRef} from 'react';
import type {SceneId,Vec2} from '../src/domain/model';
import {buildNetwork,measuredAreas,scaleConsistency,type Draft,type MeasuredScale,type NetworkInput} from './project-tools';
type Project={id:string;revision:number;data?:Record<string,unknown>;originalImage?:{id:string;mime:string;width:number;height:number}|null};
export function ProjectDetails({project,tenant,draft,file,busy,onStoreOriginal,onData,onDraft}:{project:Project;tenant:string;draft:Draft|null;file:File|null;busy:boolean;onStoreOriginal:()=>Promise<void>;onData:(data:Record<string,unknown>)=>void;onDraft:(draft:Draft)=>void}){
 const [dimensionPick,setDimensionPick]=useState<{which:'from'|'to';point:Vec2}|null>(null);
 const [tool,setTool]=useState<DrawingTool>(null);
 const lastImage=useRef(project.originalImage?.id),lastDraft=useRef(draft);
 const initial=project.data?.calibration as MeasuredScale|undefined;
 const [url,setUrl]=useState(''),[expanded,setExpanded]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [calibration,setCalibration]=useState<MeasuredScale>(initial??{a:{x:0,y:0},b:{x:draft?.width??100,y:0},lengthM:0,source:'drawing-dimension',evidence:'',confirmed:false});
 const [config,setConfig]=useState<NetworkInput>((project.data?.networkInput as NetworkInput)??{scene:'office',concurrentUsers:20,wiredPoints:0,confirmedGeometry:false});
 const restore=()=>{try{if(!project.data?.network)return null;const saved=parseProject(JSON.stringify(project.data.network));const derived=deriveProject(saved,catalog);derived.issues.unshift({code:'SITE_SURVEY_REQUIRED',severity:'blocking',message:'外轮廓暂取区域包络；墙材、门洞及射频需现场核实。该方案及报价为草案。',entityIds:[]});derived.complete=false;return {project:saved,derived}}catch{return null}};
 const [network,setNetwork]=useState<ReturnType<typeof buildNetwork>|null>(restore);
 useEffect(()=>{let active=true,objectUrl='';setUrl('');setExpanded(false);if(project.originalImage)void fetch(`/api/projects/${encodeURIComponent(project.id)}/images/${encodeURIComponent(project.originalImage.id)}`,{headers:{'X-Tenant-Id':tenant},credentials:'same-origin'}).then(async r=>{if(!r.ok)throw Error('原图无法读取，请检查登录和团队权限');const blob=await r.blob();objectUrl=URL.createObjectURL(blob);if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[tenant,project.id,project.originalImage?.id]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setExpanded(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>{if(lastImage.current===project.originalImage?.id)return;lastImage.current=project.originalImage?.id;const saved=project.data?.calibration as MeasuredScale|undefined;setCalibration(saved??{a:{x:0,y:0},b:{x:draft?.width??100,y:0},lengthM:0,source:'drawing-dimension',evidence:'',confirmed:false});setConfig(c=>({...c,confirmedGeometry:false}));setNetwork(null)},[project.originalImage?.id]);
 useEffect(()=>{if(lastDraft.current===draft)return;lastDraft.current=draft;setNetwork(null);setConfig(c=>({...c,confirmedGeometry:false}));setCalibration(c=>({...c,confirmed:false,references:draft?.dimensions?.filter(d=>d.confirmed&&(d.kind==='overall'||d.kind==='reference'))}))},[draft]);
 function updateScale(next:MeasuredScale){next={...next,canvas:draft?{width:draft.width,height:draft.height}:undefined,references:draft?.dimensions?.filter(d=>d.confirmed&&(d.kind==='overall'||d.kind==='reference'))};setCalibration(next);setNetwork(null);onData({...project.data,calibration:next,networkInput:{...config,confirmedGeometry:false},network:undefined});setConfig(c=>({...c,confirmedGeometry:false}))}
 let areas:number[]|null=null;try{if(draft)areas=measuredAreas(draft,calibration)}catch{}
 function updateConfig(next:NetworkInput){setConfig(next);setNetwork(null);onData({...project.data,networkInput:next,network:undefined})}
 const frameMatches=!!draft&&!!project.originalImage&&draft.width===project.originalImage.width&&draft.height===project.originalImage.height;
 const consistency=draft?scaleConsistency(draft,calibration):null;
 function generate(){setError('');try{if(!draft)throw Error('请先识别或载入草稿');if(!frameMatches)throw Error('原图与草稿坐标框不一致，不能生成方案');const result=buildNetwork(draft,calibration,config);setNetwork(result);onData({...project.data,calibration,networkInput:config,network:result.project})}catch(e){setError(e instanceof Error?e.message:'生成失败')}}
 function setPoint(which:'a'|'b',axis:'x'|'y',value:number){updateScale({...calibration,confirmed:false,[which]:{...calibration[which],[axis]:value}})}
 return <div className="project-details">{error&&<p role="alert">{error}</p>}<div id="team-original" className="original-panel"><h3>原始图纸对照</h3>{url?<button className="original-thumb" aria-label="放大原图" onClick={()=>setExpanded(true)}><img src={url} alt="当前项目原始图纸缩略图"/><span>点击查看原图</span></button>:<p>{project.originalImage?'正在读取原图':'此项目尚未保存原图；可重新选择文件，只保存原图而不调用模型。'}</p>}<button disabled={!file||saving||busy} onClick={()=>{setError('');setSaving(true);void onStoreOriginal().catch(e=>setError(e.message)).finally(()=>setSaving(false))}}>保存原图（不调用识别）</button><p>原图仅存于当前团队项目，刷新可读取；不写日志。已有原图的替换会重置旧草稿、标定和方案；首次补存旧项目原图需确认对应关系，可保留草稿。</p></div>{expanded&&url&&<div role="dialog" aria-modal="true" aria-label="原始图纸" className="original-modal"><button autoFocus onClick={()=>setExpanded(false)}>关闭原图</button><img src={url} alt="项目原始图纸"/></div>}
 {draft&&<><DrawingReview url={url} original={project.originalImage} draft={draft} calibration={calibration} config={config} network={network?.project} tool={tool} onError={setError} onPoint={point=>{if(tool==='a'||tool==='b')updateScale({...calibration,[tool]:point,confirmed:false});else if(tool==='dimension-from'||tool==='dimension-to')setDimensionPick({which:tool==='dimension-from'?'from':'to',point});else if(tool==='cabinet'||tool==='wan')updateConfig({...config,[tool]:point,confirmedGeometry:false});setTool(null)}}/><p>{tool?'请在原图上点击选定位置':'选择工具后在原图上点选；坐标以原始图片为准。'}</p><div className="drawing-tools">{([['a','标尺点 1'],['b','标尺点 2'],['cabinet','机柜位置'],['wan','宽带入口位置']] as const).map(([id,label])=><button key={id} disabled={!frameMatches||!url} aria-pressed={tool===id} onClick={()=>setTool(id)}>在原图选择{label}</button>)}</div><DimensionsPanel picked={dimensionPick} canPick={frameMatches&&!!url} onPick={which=>setTool(which==='from'?'dimension-from':'dimension-to')} draft={draft} original={project.originalImage} onDraft={onDraft} onScale={updateScale}/><section id="team-area" className="area-panel"><h3>面积与尺度标定</h3><p aria-label="比例尺核验状态">{consistency?.message}</p><p>像素面积不是平方米。选择草稿中一条已知长度的两端坐标，输入真实米数及依据，人工确认后计算。尺寸须对应草稿坐标，不从警告里的数字猜单位。</p><div className="scale-points">{(['a','b'] as const).map((point,i)=><div key={point}><strong>标尺点 {i+1}</strong>{(['x','y'] as const).map(axis=><label key={axis}>标尺点 {i+1} {axis}<input type="number" min="0" max={axis==='x'?draft.width:draft.height} value={calibration[point][axis]} onChange={e=>setPoint(point,axis,Number(e.target.value))}/></label>)}</div>)}</div><label>已知长度（米）<input type="number" min="0.001" step="any" value={calibration.lengthM||''} onChange={e=>updateScale({...calibration,lengthM:Number(e.target.value),confirmed:false})}/></label><label>长度依据<select value={calibration.source} onChange={e=>updateScale({...calibration,source:e.target.value as MeasuredScale['source'],confirmed:false})}><option value="drawing-dimension">原图明确尺寸标注</option><option value="field-measurement">现场实测</option></select></label><label>标注原文／实测说明<input value={calibration.evidence} maxLength={300} onChange={e=>updateScale({...calibration,evidence:e.target.value,confirmed:false})}/></label><label className="check"><input type="checkbox" checked={calibration.confirmed} onChange={e=>updateScale({...calibration,confirmed:e.target.checked})}/>我已核对长度、米单位和对应两点</label><table><thead><tr><th>房间</th><th>面积</th><th>来源／可信状态</th></tr></thead><tbody>{draft.rooms.map((room,i)=><tr key={i}><td>{room.name}</td><td>{areas?`${areas[i].toFixed(2)} m²`:'平方米待标定'}</td><td>{areas?(consistency?.status==='verified'?'双参考尺度 × 草稿多边形，非现场测绘':'单条人工标尺估算，尚未通过双参考校验'):'缺比例，不提供平方米'}</td></tr>)}</tbody></table>{draft.areaAnnotations?.map((a,i)=><p key={i}>原图面积标注候选：{draft.rooms[a.roomIndex]?.name} {a.value} m²；原文“{a.evidence}”；模型置信 {(a.confidence*100).toFixed(0)}%，待人工核实（不替代标定）</p>)}<p>房间面积不等于建筑面积；重叠区域不可直接相加。修改后点击上方“保存人工校正”。</p></section>
 <section id="team-network" className="network-panel"><h3>下一步：生成组网草案</h3>{!!project.data?.network&&<p>该项目已保存组网草案；核对需求后可重新生成查看布点、拓扑和预算。</p>}<p>复用原 APP 的 AP 规划、布线、拓扑与报价引擎。当前单层、Wi-Fi6、有线信息点；监控未接入。请在原图指定机柜与宽带入口，外轮廓暂按区域包络矩形；须现场核实。</p><label>业务场景<select value={config.scene} onChange={e=>{updateConfig({...config,scene:e.target.value as SceneId})}}>{[['restaurant','餐饮'],['office','办公'],['gym','健身'],['hotel','酒店'],['retail','零售']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>预计同时上网人数<input type="number" min="0" max="10000" value={config.concurrentUsers} onChange={e=>{updateConfig({...config,concurrentUsers:Number(e.target.value)})}}/></label><label>有线信息点数量<input type="number" min="0" max="10000" value={config.wiredPoints} onChange={e=>{updateConfig({...config,wiredPoints:Number(e.target.value)})}}/></label><label className="check"><input type="checkbox" checked={config.confirmedGeometry} onChange={e=>{updateConfig({...config,confirmedGeometry:e.target.checked})}}/>我已核对区域边界、实体墙、门洞及原图机柜／宽带入口位置</label><button disabled={!areas||!config.confirmedGeometry||!frameMatches||!config.cabinet||!config.wan||consistency?.status!=='verified'} onClick={generate}>生成布点、拓扑与预算</button>{network&&<><h4>布点与线路草案</h4><p>方案点位已叠加到上方原图，AP、有线信息点和线路保持原始图片坐标。</p><p>预算草案 ¥{(network.derived.totalCents/100).toFixed(2)}；包含待核实目录单价，不是成交价或施工承诺。</p><table><thead><tr><th>设备／材料</th><th>数量</th><th>小计</th></tr></thead><tbody>{network.derived.bom.map(line=><tr key={line.id}><td>{line.name}</td><td>{line.quantity} {line.unit}</td><td>¥{(line.subtotalCents/100).toFixed(2)}</td></tr>)}</tbody></table><h4>拓扑连接</h4><ul>{network.derived.topology.edges.map((edge,i)=><li key={i}>{network.derived.topology.nodes.find(n=>n.id===edge.from)?.label??edge.from} → {network.derived.topology.nodes.find(n=>n.id===edge.to)?.label??edge.to}：{edge.label}</li>)}</ul>{network.derived.issues.map((issue,i)=><p key={i}>{issue.severity==='blocking'?'需处理':'提示'}：{issue.message}</p>)}<p>点击上方“保存人工校正”保存标定、需求和方案；重新载入后恢复已保存方案和预算。无比例、房间重叠和无效边界会阻止生成。</p></>}</section></>}
 </div>
}
