import type {Vec2,SceneId,RecognitionDraft,RoomUse} from '../src/domain/model';
import {polygonArea,interiorLabelPoint} from '../src/domain/geometry';
import {knownLength,calibrateDraft} from '../src/recognition/calibration';
import {createDraftEdits} from '../src/recognition/draft';
import {createScene} from '../src/scenes';
import {planFloor} from '../src/planning/ap';
import {routeProject} from '../src/planning/routing';
import {deriveProject} from '../src/quote/derive';
import {catalog} from '../src/catalog/models';
export type Dimension={value:number;unit:'mm'|'m'|'unknown';kind:'overall'|'chain'|'opening'|'wall-thickness'|'furniture'|'reference'|'elevation';from:Vec2;to:Vec2;evidence:string;confidence:number;source:'model'|'manual';rawLabel?:string;chainId?:string;confirmed?:boolean};
export type Draft={width:number;height:number;rooms:{name:string;use:string;boundary?:'functional'|'physical'|'unknown';polygon:Vec2[]}[];walls:{from:Vec2;to:Vec2}[];warnings:string[];dimensions?:Dimension[];openings?:{from:Vec2;to:Vec2;evidence:string;confidence:number;confirmed:boolean;roomIndices?:number[]}[];areaAnnotations?:{roomIndex:number;value:number;unit:'m2';evidence:string;confidence:number}[]};
export type MeasuredScale={a:Vec2;b:Vec2;lengthM:number;source:'drawing-dimension'|'field-measurement';evidence:string;confirmed:boolean};
export type NetworkInput={scene:SceneId;concurrentUsers:number;wiredPoints:number;confirmedGeometry:boolean;cabinet?:Vec2;wan?:Vec2};
function scale(draft:Draft,input:MeasuredScale){if(!input.confirmed||!input.evidence.trim()||!['drawing-dimension','field-measurement'].includes(input.source)||!Number.isFinite(input.lengthM)||input.lengthM<=0)throw Error('请人工确认有效长度及依据，不能从像素猜平方米');for(const p of [input.a,input.b])if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.y<0||p.x>draft.width||p.y>draft.height)throw Error('标尺点超出图纸');const result=knownLength(input.a,input.b,input.lengthM);if(result.kind==='unset')throw Error('两标尺点距离至少大于1像素，且长度必须有效');return result}
export function measuredAreas(draft:Draft,input:MeasuredScale|null){if(!input?.confirmed)return null;const s=scale(draft,input).metersPerPixel!;return draft.rooms.map(room=>polygonArea(room.polygon)*s*s)}
export function buildNetwork(draft:Draft,input:MeasuredScale,config:NetworkInput){if(!config.confirmedGeometry)throw Error('请先核对房间、外轮廓和机柜/宽带入口位置');if(!draft.rooms.length)throw Error('至少需要一个房间');for(const value of [config.concurrentUsers,config.wiredPoints])if(!Number.isSafeInteger(value)||value<0||value>10000)throw Error('终端需求必须为0..10000整数');const calibration=scale(draft,input),points=draft.rooms.flatMap(r=>r.polygon);const xmin=Math.min(...points.map(p=>p.x)),xmax=Math.max(...points.map(p=>p.x)),ymin=Math.min(...points.map(p=>p.y)),ymax=Math.max(...points.map(p=>p.y));
 if(draft.openings?.some(o=>!o.confirmed||!o.roomIndices?.length))throw Error('请先核对每个门洞并关联房间，不能忽略门洞生成方案');
 for(const o of draft.openings??[])for(const w of draft.walls){const dx=o.to.x-o.from.x,dy=o.to.y-o.from.y,len=Math.hypot(dx,dy),distance=(p:Vec2)=>Math.abs(dx*(p.y-o.from.y)-dy*(p.x-o.from.x))/len;if(distance(w.from)<0.001&&distance(w.to)<0.001){const project=(p:Vec2)=>((p.x-o.from.x)*dx+(p.y-o.from.y)*dy)/len;const a=project(w.from),b=project(w.to);if(Math.min(len,Math.max(a,b))-Math.max(0,Math.min(a,b))>0.001)throw Error('实体墙跨越门洞，请先拆分或校正墙线');}}
 const recognition:RecognitionDraft={document:{assetId:'server-original',mime:'image/png',widthPx:draft.width,heightPx:draft.height,page:0},text:[],boundaryPx:[{x:xmin,y:ymin},{x:xmax,y:ymin},{x:xmax,y:ymax},{x:xmin,y:ymax}],roomsPx:draft.rooms.map((r,i)=>({...r,id:`room-${i}`,use:r.use as RoomUse,confirmed:true,provenance:'manual'})),wallsPx:draft.walls.map((w,i)=>({...w,id:`wall-${i}`,material:'unknown',confirmed:true,provenance:'manual'})),openingsPx:(draft.openings??[]).map((o,i)=>({id:`opening-${i}`,at:{x:(o.from.x+o.to.x)/2,y:(o.from.y+o.to.y)/2},widthPx:Math.hypot(o.to.x-o.from.x,o.to.y-o.from.y),roomIds:(o.roomIndices??[]).map(j=>`room-${j}`),entrance:o.roomIndices?.length===1,confirmed:o.confirmed,provenance:'manual'})),issues:[]};
 const edits=createDraftEdits(recognition),suggested=interiorLabelPoint(draft.rooms[0].polygon);edits.cabinetPx=config.cabinet??suggested;edits.wanPx=config.wan??suggested;
 const floor=calibrateDraft(recognition,calibration,edits);floor.demand={employees:0,visitors:0,terminals:config.concurrentUsers,concurrentUsers:config.concurrentUsers,wiredPoints:config.wiredPoints};const p=createScene(config.scene);p.floors=[floor];p.business=[];p.settings.monitoring=false;p.name='图纸组网草案';p.floors=[planFloor(floor,p.settings).floor];const routed=routeProject(p).project,derived=deriveProject(routed,catalog);derived.issues.unshift({code:'SITE_SURVEY_REQUIRED',severity:'blocking',message:'外轮廓暂取房间包络矩形；门洞、墙材、机柜/宽带入口和射频须现场核实。该方案及报价为草案。',entityIds:[]});derived.complete=false;return {project:routed,derived};}

export function dimensionMeters(d:Dimension){if(d.kind==='elevation')throw Error('标高不能用作平面长度或面积标尺');if(!Number.isFinite(d.value)||d.value<=0||!['mm','m'].includes(d.unit))throw Error('请确认这条尺寸的mm或m单位，不从像素猜长度');return d.unit==='mm'?d.value/1000:d.value}
export function dimensionCalibration(draft:Draft,d:Dimension):MeasuredScale{const next:MeasuredScale={a:d.from,b:d.to,lengthM:dimensionMeters(d),source:'drawing-dimension',evidence:d.evidence,confirmed:false};scale(draft,{...next,confirmed:true});return next}
export function parseDimensionCandidates(value:unknown,draft:Draft):Dimension[]{if(!Array.isArray(value)||value.length>200)throw Error('尺寸候选必须是最多200项的数组');const allowed=['value','unit','kind','from','to','evidence','confidence','source'];return value.map(v=>{if(!v||typeof v!=='object'||Object.keys(v).some(k=>!allowed.includes(k)&&!['rawLabel','chainId','confirmed'].includes(k))||allowed.some(k=>!Object.prototype.hasOwnProperty.call(v,k))||!Number.isFinite(v.value)||v.value<=0||v.value>100000000||!['mm','m','unknown'].includes(v.unit)||!['overall','chain','opening','wall-thickness','furniture','reference','elevation'].includes(v.kind)||!['manual','model'].includes(v.source)||typeof v.evidence!=='string'||!v.evidence.trim()||v.evidence.length>300||!Number.isFinite(v.confidence)||v.confidence<0||v.confidence>1)throw Error('尺寸候选的数值、单位或依据不合规');for(const k of ['rawLabel','chainId'])if(v[k]!==undefined&&(typeof v[k]!=='string'||!v[k].trim()||v[k].length>300))throw Error('标注原文或尺寸链标识无效');if(v.confirmed!==undefined&&typeof v.confirmed!=='boolean')throw Error('尺寸确认状态无效');for(const p of [v.from,v.to])if(!p||Object.keys(p).length!==2||!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.y<0||p.x>draft.width||p.y>draft.height)throw Error('尺寸候选端点超出草稿坐标框');if(Math.hypot(v.from.x-v.to.x,v.from.y-v.to.y)<=0)throw Error('尺寸候选两点必须不同');return v as Dimension})}

export function dimensionChainMeters(dimensions:Dimension[],chainId:string){const chain=dimensions.filter(d=>d.chainId===chainId&&d.kind==='chain');if(!chain.length)throw Error('没有对应尺寸链');const seen=new Set<string>();let total=0;for(const d of chain){const key=[`${d.from.x},${d.from.y}`,`${d.to.x},${d.to.y}`].sort().join(':');if(seen.has(key))throw Error('尺寸链包含重复边段，不能重复累计');seen.add(key);total+=dimensionMeters(d);}return total}

export function removeDraftRoom(draft:Draft,index:number):Draft{if(!Number.isInteger(index)||index<0||index>=draft.rooms.length)throw Error('房间序号无效');return {...draft,rooms:draft.rooms.filter((_,i)=>i!==index),areaAnnotations:draft.areaAnnotations?.filter(a=>a.roomIndex!==index).map(a=>({...a,roomIndex:a.roomIndex>index?a.roomIndex-1:a.roomIndex})),openings:draft.openings?.map(o=>{const roomIndices=o.roomIndices?.filter(i=>i!==index).map(i=>i>index?i-1:i);return {...o,confirmed:false,roomIndices:roomIndices?.length?roomIndices:undefined}})}}
