import type {Vec2,SceneId,RecognitionDraft,RoomUse} from '../src/domain/model';
import {polygonArea} from '../src/domain/geometry';
import {knownLength,calibrateDraft} from '../src/recognition/calibration';
import {createDraftEdits} from '../src/recognition/draft';
import {createScene} from '../src/scenes';
import {planFloor} from '../src/planning/ap';
import {routeProject} from '../src/planning/routing';
import {deriveProject} from '../src/quote/derive';
import {catalog} from '../src/catalog/models';
export type Dimension={value:number;unit:'mm'|'m'|'unknown';kind:'overall'|'chain'|'opening'|'wall-thickness'|'furniture'|'reference'|'elevation';from:Vec2;to:Vec2;evidence:string;confidence:number;source:'model'|'manual';rawLabel?:string;chainId?:string;confirmed?:boolean};
export type Draft={width:number;height:number;rooms:{name:string;use:string;boundary?:'functional'|'physical'|'unknown';polygon:Vec2[]}[];walls:{from:Vec2;to:Vec2}[];warnings:string[];dimensions?:Dimension[];openings?:{from:Vec2;to:Vec2;evidence:string;confidence:number;confirmed:boolean;roomIndices?:number[]}[];areaAnnotations?:{roomIndex:number;value:number;unit:'m2';evidence:string;confidence:number}[]};
export type MeasuredScale={a:Vec2;b:Vec2;lengthM:number;source:'drawing-dimension'|'field-measurement';evidence:string;confirmed:boolean;canvas?:{width:number;height:number};references?:Dimension[]};
export type NetworkInput={scene:SceneId;concurrentUsers:number;wiredPoints:number;confirmedGeometry:boolean;cabinet?:Vec2;wan?:Vec2};
function scale(draft:Draft,input:MeasuredScale){if(input.canvas&&(input.canvas.width!==draft.width||input.canvas.height!==draft.height))throw Error('标尺与原图坐标框不一致');if(!input.confirmed||!input.evidence.trim()||!['drawing-dimension','field-measurement'].includes(input.source)||!Number.isFinite(input.lengthM)||input.lengthM<=0)throw Error('标尺证据缺失或未确认：请核对长度、单位、依据及对应端点');for(const p of [input.a,input.b])if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.y<0||p.x>draft.width||p.y>draft.height)throw Error('标尺点超出图纸');const result=knownLength(input.a,input.b,input.lengthM);if(result.kind==='unset')throw Error('两标尺点距离至少大于1像素，且长度必须有效');return result}
export type ScaleConsistency={status:'unverified'|'verified'|'review'|'conflict';relativeError:number|null;message:string};
/** Engineering gates, not surveying accuracy guarantees: long independent spans and <=1% agreement. */
export function scaleConsistency(draft:Draft,input:MeasuredScale):ScaleConsistency{
 const result=(status:ScaleConsistency['status'],message:string,relativeError:number|null=null)=>({status,message,relativeError});
 let base:number;try{base=scale(draft,input).metersPerPixel!}catch{const mismatch=input.canvas&&(input.canvas.width!==draft.width||input.canvas.height!==draft.height);return result(mismatch?'conflict':'unverified',mismatch?'标尺与原图坐标框不一致':'标尺证据缺失或未确认')}
 if(!input.canvas||input.canvas.width!==draft.width||input.canvas.height!==draft.height)return result('conflict','标尺与原图坐标框不一致，请重新确认原图端点');
 const minSpan=Math.max(10,Math.hypot(draft.width,draft.height)*0.1);
 const refs:(Dimension & {ratio:number;dx:number;dy:number})[]=[];
 for(const d of input.references??[]){if(!d.confirmed||!['overall','reference'].includes(d.kind)||!d.evidence.trim())continue;try{const c=dimensionCalibration(draft,d);const dx=d.to.x-d.from.x,dy=d.to.y-d.from.y,len=Math.hypot(dx,dy);if(len>=minSpan)refs.push({...d,ratio:c.lengthM/len,dx:dx/len,dy:dy/len})}catch{}}
 const independent=refs.some((a,i)=>refs.slice(i+1).some(b=>Math.abs(a.dx*b.dy-a.dy*b.dx)>=0.5));
 if(!independent)return result('unverified','请确认至少两条不同方向的长尺寸（总体或参考尺寸），不能用重复或同轴尺寸代替');
 const ratios=[base,...refs.map(r=>r.ratio)],relativeError=(Math.max(...ratios)-Math.min(...ratios))/Math.min(...ratios);
 if(relativeError>0.02+1e-9)return result('conflict','不同方向尺寸比例差超过2%，请检查端点、单位或图纸变形',relativeError);
 if(relativeError>0.01+1e-9)return result('review','尺寸比例差为1%至2%，请校正参考尺寸后再生成',relativeError);
 return result('verified','两条独立尺寸一致（差异不超过1%）；仍需现场核实',relativeError);
}
export function originalPointerToDraft(point:{clientX:number;clientY:number},rect:{left:number;top:number;width:number;height:number},original:{width:number;height:number},draft:Pick<Draft,'width'|'height'>):Vec2{if(original.width!==draft.width||original.height!==draft.height)throw Error('原图与草稿坐标框不一致，不能自动缩放端点；请先重新识别或载入匹配坐标框的草稿');if(![point.clientX,point.clientY,rect.left,rect.top,rect.width,rect.height,original.width,original.height].every(Number.isFinite)||rect.width<=0||rect.height<=0||original.width<=0||original.height<=0)throw Error('原图显示尺寸无效');const x=point.clientX-rect.left,y=point.clientY-rect.top;if(x<0||y<0||x>rect.width||y>rect.height)throw Error('请在原图范围内选择端点');return {x:x/rect.width*original.width,y:y/rect.height*original.height}}
export function metersToDraft(draft:Draft,input:MeasuredScale,point:Vec2):Vec2{const s=scale(draft,input).metersPerPixel!;if(!Number.isFinite(point.x)||!Number.isFinite(point.y))throw Error('方案点位无效');return {x:point.x/s,y:point.y/s}}
export function measuredAreas(draft:Draft,input:MeasuredScale|null){if(!input?.confirmed)return null;const s=scale(draft,input).metersPerPixel!;return draft.rooms.map(room=>polygonArea(room.polygon)*s*s)}
export function buildNetwork(draft:Draft,input:MeasuredScale,config:NetworkInput){if(!config.confirmedGeometry)throw Error('请先核对房间、外轮廓和机柜/宽带入口位置');if(!draft.rooms.length)throw Error('至少需要一个房间');if(!config.cabinet||!config.wan)throw Error('请在原图明确标记机柜与宽带入口位置');for(const value of [config.concurrentUsers,config.wiredPoints])if(!Number.isSafeInteger(value)||value<0||value>10000)throw Error('终端需求必须为0..10000整数');const consistency=scaleConsistency(draft,input);if(consistency.status!=='verified')throw Error(consistency.message);const calibration=scale(draft,input),points=draft.rooms.flatMap(r=>r.polygon);const xmin=Math.min(...points.map(p=>p.x)),xmax=Math.max(...points.map(p=>p.x)),ymin=Math.min(...points.map(p=>p.y)),ymax=Math.max(...points.map(p=>p.y));
 if(draft.openings?.some(o=>!o.confirmed||!o.roomIndices?.length))throw Error('请先核对每个门洞并关联房间，不能忽略门洞生成方案');
 for(const o of draft.openings??[])for(const w of draft.walls){const dx=o.to.x-o.from.x,dy=o.to.y-o.from.y,len=Math.hypot(dx,dy),distance=(p:Vec2)=>Math.abs(dx*(p.y-o.from.y)-dy*(p.x-o.from.x))/len;if(distance(w.from)<0.001&&distance(w.to)<0.001){const project=(p:Vec2)=>((p.x-o.from.x)*dx+(p.y-o.from.y)*dy)/len;const a=project(w.from),b=project(w.to);if(Math.min(len,Math.max(a,b))-Math.max(0,Math.min(a,b))>0.001)throw Error('实体墙跨越门洞，请先拆分或校正墙线');}}
 const recognition:RecognitionDraft={document:{assetId:'server-original',mime:'image/png',widthPx:draft.width,heightPx:draft.height,page:0},text:[],boundaryPx:[{x:xmin,y:ymin},{x:xmax,y:ymin},{x:xmax,y:ymax},{x:xmin,y:ymax}],roomsPx:draft.rooms.map((r,i)=>({...r,id:`room-${i}`,use:r.use as RoomUse,confirmed:true,provenance:'manual'})),wallsPx:draft.walls.map((w,i)=>({...w,id:`wall-${i}`,material:'unknown',confirmed:true,provenance:'manual'})),openingsPx:(draft.openings??[]).map((o,i)=>({id:`opening-${i}`,at:{x:(o.from.x+o.to.x)/2,y:(o.from.y+o.to.y)/2},widthPx:Math.hypot(o.to.x-o.from.x,o.to.y-o.from.y),roomIds:(o.roomIndices??[]).map(j=>`room-${j}`),entrance:o.roomIndices?.length===1,confirmed:o.confirmed,provenance:'manual'})),issues:[]};
 const edits=createDraftEdits(recognition);edits.cabinetPx=config.cabinet;edits.wanPx=config.wan;
 const floor=calibrateDraft(recognition,calibration,edits);floor.demand={employees:0,visitors:0,terminals:config.concurrentUsers,concurrentUsers:config.concurrentUsers,wiredPoints:config.wiredPoints};const p=createScene(config.scene);p.floors=[floor];p.business=[];p.settings.monitoring=false;p.name='图纸组网草案';p.floors=[planFloor(floor,p.settings).floor];const routed=routeProject(p).project,derived=deriveProject(routed,catalog);derived.issues.unshift({code:'SITE_SURVEY_REQUIRED',severity:'blocking',message:'外轮廓暂取房间包络矩形；门洞、墙材、机柜/宽带入口和射频须现场核实。该方案及报价为草案。',entityIds:[]});derived.complete=false;return {project:routed,derived};}

export function dimensionMeters(d:Dimension){if(d.kind==='elevation')throw Error('标高不能用作平面长度或面积标尺');if(!Number.isFinite(d.value)||d.value<=0||!['mm','m'].includes(d.unit))throw Error('请确认这条尺寸的mm或m单位，不从像素猜长度');return d.unit==='mm'?d.value/1000:d.value}
export function dimensionCalibration(draft:Draft,d:Dimension):MeasuredScale{const next:MeasuredScale={a:d.from,b:d.to,lengthM:dimensionMeters(d),source:'drawing-dimension',evidence:d.evidence,confirmed:false,canvas:{width:draft.width,height:draft.height}};scale(draft,{...next,confirmed:true});return next}
export function parseDimensionCandidates(value:unknown,draft:Draft):Dimension[]{if(!Array.isArray(value)||value.length>200)throw Error('尺寸候选必须是最多200项的数组');const allowed=['value','unit','kind','from','to','evidence','confidence','source'];return value.map(v=>{if(!v||typeof v!=='object'||Object.keys(v).some(k=>!allowed.includes(k)&&!['rawLabel','chainId','confirmed'].includes(k))||allowed.some(k=>!Object.prototype.hasOwnProperty.call(v,k))||!Number.isFinite(v.value)||v.value<=0||v.value>100000000||!['mm','m','unknown'].includes(v.unit)||!['overall','chain','opening','wall-thickness','furniture','reference','elevation'].includes(v.kind)||!['manual','model'].includes(v.source)||typeof v.evidence!=='string'||!v.evidence.trim()||v.evidence.length>300||!Number.isFinite(v.confidence)||v.confidence<0||v.confidence>1)throw Error('尺寸候选的数值、单位或依据不合规');for(const k of ['rawLabel','chainId'])if(v[k]!==undefined&&(typeof v[k]!=='string'||!v[k].trim()||v[k].length>300))throw Error('标注原文或尺寸链标识无效');if(v.confirmed!==undefined&&typeof v.confirmed!=='boolean')throw Error('尺寸确认状态无效');for(const p of [v.from,v.to])if(!p||Object.keys(p).length!==2||!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.y<0||p.x>draft.width||p.y>draft.height)throw Error('尺寸候选端点超出草稿坐标框');if(Math.hypot(v.from.x-v.to.x,v.from.y-v.to.y)<=0)throw Error('尺寸候选两点必须不同');return v as Dimension})}

export function dimensionChainMeters(dimensions:Dimension[],chainId:string){
 const chain=dimensions.filter(d=>d.chainId===chainId&&d.kind==='chain');if(!chain.length)throw Error('没有对应尺寸链');
 const origin=chain[0].from,dx=chain[0].to.x-origin.x,dy=chain[0].to.y-origin.y,length=Math.hypot(dx,dy);if(!Number.isFinite(length)||length<=0)throw Error('尺寸链端点无效');
 const projection=(p:Vec2)=>((p.x-origin.x)*dx+(p.y-origin.y)*dy)/length;
 const intervals=chain.map(d=>{for(const p of [d.from,d.to])if(!Number.isFinite(p.x)||!Number.isFinite(p.y)||Math.abs(dx*(p.y-origin.y)-dy*(p.x-origin.x))/length>0.001)throw Error('尺寸链必须共线');const a=projection(d.from),b=projection(d.to);if(Math.abs(a-b)<=0.001)throw Error('尺寸链包含零长度边段');return {start:Math.min(a,b),end:Math.max(a,b),value:dimensionMeters(d)}}).sort((a,b)=>a.start-b.start);
 for(let i=1;i<intervals.length;i++){const gap=intervals[i].start-intervals[i-1].end;if(gap< -0.001)throw Error('尺寸链包含重复或重叠边段，不能重复累计');if(gap>0.001)throw Error('尺寸链不连续，不能累计缺失边段');}
 return intervals.reduce((sum,d)=>sum+d.value,0);
}

export function removeDraftRoom(draft:Draft,index:number):Draft{if(!Number.isInteger(index)||index<0||index>=draft.rooms.length)throw Error('房间序号无效');return {...draft,rooms:draft.rooms.filter((_,i)=>i!==index),areaAnnotations:draft.areaAnnotations?.filter(a=>a.roomIndex!==index).map(a=>({...a,roomIndex:a.roomIndex>index?a.roomIndex-1:a.roomIndex})),openings:draft.openings?.map(o=>{const roomIndices=o.roomIndices?.filter(i=>i!==index).map(i=>i>index?i-1:i);return {...o,confirmed:false,roomIndices:roomIndices?.length?roomIndices:undefined}})}}
