import {useState} from 'react';
import type {Draft} from './project-tools';
type Source={state:'legacy-unverified'|'matched'|'different'|'no-original';projectRevision?:number};
type Job={id:string;createdAt?:string;status:string;source:Source;draft?:Draft};
const sourceText=(source:Source)=>source.state==='matched'?'来源已核验：图片字节与当前原图一致':source.state==='different'?'来源不一致：结果来自不同原图，不能采用到当前原图':source.state==='no-original'?'当前没有原图，无法对照采用':'旧结果：原图对应关系未验证，不能凭房间相似认定匹配';
export function RecognitionHistory({projectId,originalId,dirty,busy,api,onAdopt}:{projectId:string;originalId?:string;dirty:boolean;busy:boolean;api:(path:string)=>Promise<any>;onAdopt:(job:Job)=>Promise<void>}){
 const [jobs,setJobs]=useState<Job[]|null>(null),[preview,setPreview]=useState<Job|null>(null),[checked,setChecked]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function read(path:string){setError('');setLoading(true);try{return await api(path)}catch(e){setError(e instanceof Error?e.message:'历史结果读取失败')}finally{setLoading(false)}}
 return <section id="team-history" className="recognition-history"><h3>历史识别结果 · 只读预览</h3><p>预览不修改项目，也不调用模型。采用前请对照原图，检查房间用途与边界。</p><button disabled={busy||loading} onClick={()=>void read(`/projects/${encodeURIComponent(projectId)}/recognitions`).then(r=>{if(r)setJobs(r.recognitions)})}>查看历史识别结果</button>{error&&<p role="alert">{error}</p>}{jobs&&(!jobs.length?<p>暂无历史结果。若需新识别，请选择文件并明确同意外传及额度使用。</p>:<ul>{jobs.map(job=><li key={job.id}><span>{job.createdAt?new Date(job.createdAt).toLocaleString('zh-CN'):'历史任务'} · 待人工确认</span><p>{sourceText(job.source)}</p><button disabled={busy||loading} onClick={()=>{setPreview(null);setChecked(false);void read(`/projects/${encodeURIComponent(projectId)}/recognitions/${encodeURIComponent(job.id)}`).then(r=>{if(r)setPreview({...job,...r.recognition})})}}>预览此历史结果</button></li>)}</ul>)}{preview?.draft&&<div className="history-preview"><h4>历史草稿预览（尚未采用）</h4><p>{sourceText(preview.source)}{preview.source.projectRevision!==undefined&&` · 发起时项目版本 ${preview.source.projectRevision}`}</p><svg role="img" aria-label="历史识别草稿预览" viewBox={`0 0 ${preview.draft.width} ${preview.draft.height}`}>{preview.draft.rooms.map((room,i)=><g key={i}><polygon points={room.polygon.map(p=>`${p.x},${p.y}`).join(' ')}/><text x={room.polygon.reduce((n,p)=>n+p.x,0)/room.polygon.length} y={room.polygon.reduce((n,p)=>n+p.y,0)/room.polygon.length}>{room.name}</text></g>)}{preview.draft.walls.map((w,i)=><line key={i} x1={w.from.x} y1={w.from.y} x2={w.to.x} y2={w.to.y}/>)}</svg><ul>{preview.draft.rooms.map((r,i)=><li key={i}>{r.name} · 待核对用途与边界</li>)}</ul><details><summary>查看历史识别警告（可能包含模型原文）</summary>{preview.draft.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>{dirty&&<p>当前有未保存内容，请先点“保存人工校正”。预览不会覆盖这些修改。</p>}<label className="check"><input type="checkbox" disabled={!originalId||dirty||busy||preview.source.state==='different'} checked={checked} onChange={e=>setChecked(e.target.checked)}/>我已对照当前原图核对此历史草稿；接受其来源提示并确认采用</label><p>采用会写入项目草稿、清除旧标定与组网方案、增加保存版本。已有草稿会被替换，必须再次确认。</p><button disabled={!checked||dirty||busy||!originalId||preview.source.state==='different'} onClick={()=>{if(!window.confirm('确认采用预览的历史草稿并保存？这会替换已有草稿、清除面积标定和组网方案。旧结果的原图对应关系仍不自动变为已核验。'))return;void onAdopt(preview).then(()=>setChecked(false))}}>确认采用并保存历史草稿</button></div>}</section>
}
