import type {Project,DerivedProject} from '../domain/model';
import {catalog} from '../catalog/models';
import {floorSvg,escapeXml as e,kindName} from './svg';
const money=(n:number)=>(n/100).toFixed(2);
const chunks=<T>(items:T[],size:number)=>Array.from({length:Math.ceil(items.length/size)},(_,i)=>items.slice(i*size,(i+1)*size));
export function reportHtml(project:Project,derived:DerivedProject,images:Record<string,string>={}):string{
 const pages:{title:string;body:string}[]=[];
 const add=(title:string,body:string)=>pages.push({title,body});
 add('组网方案与预算',`<div class="kicker">NETATELIER / 离线方案</div><h1>${e(project.name)}</h1><p class="total">预算合计 ¥${money(derived.totalCents)}</p><p class="warning">${derived.complete?'预算估算；施工前须现场复核':'存在未确认事项，本预算不可直接作为施工依据'}</p><p>工程更新时间：${e(project.updatedAt)}<br/>组网工坊 0.1.0 · ${project.floors.length}层 · 币种 CNY 人民币</p><table><tbody>${Object.entries(derived.totals).map(([key,n])=>`<tr><td>${({network:'组网必要设备',monitoring:'监控',materials:'布线及材料',labor:'施工安装调试',optional:'手动加入的可选设备'} as Record<string,string>)[key]}</td><td>¥${money(n)}</td></tr>`).join('')}</tbody></table><h2>范围与事实边界</h2><p>默认预算仅计算实际点位、配套网络/监控设备、线材及人工。未加入的经营设备推荐不计费。商品单价为有日期的参考/估算，不是实时电商成交价，可在应用中改价。</p><p>本应用输出辅助设计，不代替现场射频测试、隐私审核、结构/消防/强电设计或施工合同。不含运营商月租、土建破墙恢复、税运差异、高空或夜间作业溢价。</p><p>铜缆按独立路径、两端预留、引下及一次损耗计量；共用线槽按物理路径去重。全项目净铜缆 ${derived.quantities.netCableM.toFixed(2)}m，含余量 ${derived.quantities.cableWithReserveM.toFixed(2)}m；线槽 ${derived.quantities.trayM.toFixed(2)}m；楼层主干 ${derived.quantities.backboneM.toFixed(2)}m。</p>`);
 for(const f of project.floors){
  add(`${f.name} · 点位与布线`,`<div data-floor="${e(f.id)}">${floorSvg(project,f.id,images,false)}</div><p>本页为该楼层实际工程点。摄像头使用半球标记，不表示全向无死角；风险与缺口请见待确认清单。</p><p>${e(f.notes??'')}</p><p>比例：${e(f.calibration.kind)}；层高标高 ${f.elevationM}m。人数需求 ${f.demand.concurrentUsers}人同时在线，终端 ${f.demand.terminals}台。</p>`);
  const entries=[...f.rooms.map((r,i)=>[`R${i+1}`,r.name,r.use,r.confirmed?'已确认':'待确认']),...f.devices.filter(d=>project.settings.monitoring||d.kind!=='camera').map(d=>[d.label,kindName(d.kind),`${d.positionM.x.toFixed(2)}, ${d.positionM.y.toFixed(2)}m`,d.locked?'已锁定':d.source==='manual'?'手工点位':'自动点位'])];
  // Leave space for Android CJK font metrics; 26 rows overflowed A4 on the
  // native print renderer even though desktop Chromium's layout check passed.
  for(const [i,part] of chunks(entries,20).entries())add(`${f.name} · 房间及点位明细 ${i+1}`,`<table><thead><tr><th>编号/标签</th><th>名称/类别</th><th>用途/坐标</th><th>状态</th></tr></thead><tbody>${part.map(row=>`<tr>${row.map(c=>`<td>${e(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`);
 }
 const graph=derived.topology;
 for(const [i,part] of chunks(graph.edges,10).entries())add(`网络拓扑 · 连接分图 ${i+1}`,`<p>所有实际连接按页展开，端口来自当前分配，跨页沿用相同设备名/ID。未推断 VLAN。</p>${part.map(edge=>{const a=graph.nodes.find(n=>n.id===edge.from),b=graph.nodes.find(n=>n.id===edge.to);return `<div class="edge"><div>${e(a?.label??edge.from)}<small>${e(a?.id??'')}</small></div><span>→<small>${e(edge.label)}</small></span><div>${e(b?.label??edge.to)}<small>${e(b?.id??'')}</small></div></div>`;}).join('')}`);
 const unlinked=graph.nodes.filter(n=>!graph.edges.some(e=>e.from===n.id||e.to===n.id));if(unlinked.length)add('网络拓扑 · 尚无连接的节点',unlinked.map(n=>`<p>${e(n.label)} · ${e(n.id)}</p>`).join(''));
 for(const [i,part] of chunks(derived.bom,9).entries())add(`设备、材料与施工清单 ${i+1}`,`<table class="bom"><thead><tr><th>项目 / 型号与依据</th><th>数量</th><th>单价(元)</th><th>小计(元)</th></tr></thead><tbody>${part.map(l=>{const m=catalog.find(m=>m.id===l.modelId);return `<tr data-bom="${e(l.id)}"><td><strong>${e(l.name)}</strong><small>${e(m?m.brand+' '+m.model:l.modelId)} · ${e(project.floors.find(f=>f.id===l.floorId)?.name??'全项目')}</small><small>${e(l.basis)} · ${l.priceKind==='user'?'人工改价':l.priceKind==='estimate'?'待核实估算':'页面参考'}</small></td><td>${l.quantity}${e(l.unit)}</td><td>${money(l.unitCents)}</td><td>${money(l.subtotalCents)}</td></tr>`;}).join('')}</tbody></table><p class="right">全项目合计 ¥${money(derived.totalCents)}；本页为清单的一部分。</p>`);
 const prices=[...new Set(derived.bom.map(l=>l.modelId))].map(id=>catalog.find(m=>m.id===id)).filter(m=>!!m);
 for(const [i,part] of chunks(prices,4).entries())add(`价格来源与条件 ${i+1}`,part.map(m=>`<article><h3>${e(m.brand)} ${e(m.model)}</h3><p>核查日期 ${e(m.checkedAt??'待确认')} · ${m.priceKind==='estimate'?'估算预算（非核实成交价）':'页面参考价'} · 目录 ¥${money(m.unitCents)}${project.priceOverrides[m.id]!==undefined?` · 本项目改价 ¥${money(project.priceOverrides[m.id])}`:''}</p><p>${e(m.conditions)}</p><p class="url">价格参考：${e(m.sourceUrl??'无可核实零售页面；请以当地询价为准')}<br/>规格：${e(m.specificationUrl??'待核实')}</p>${m.priceReferences?.map(r=>`<p class="url">${e(r.checkedAt)} · ${r.kind==='procurement-cap'?'采购限价，非零售价':'页面参考'} ¥${money(r.observedCents)} · ${e(r.conditions)}<br/>${e(r.url)}</p>`).join('')??''}</article>`).join(''));
 for(const [i,part] of chunks(derived.issues,9).entries())add(`待确认事项与计算假设 ${i+1}`,part.map(issue=>`<article class="issue"><strong>${issue.severity==='blocking'?'待确认 / 不可直接施工':'说明'} · ${e(issue.code)}</strong><p>${e(issue.message)}</p>${issue.entityIds.length?`<small>关联：${e(issue.entityIds.join('、'))}</small>`:''}</article>`).join(''));
 return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; font-src data:; style-src 'unsafe-inline'"/><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;color:#223d30;font:10pt sans-serif}section{page-break-after:always;min-height:267mm;position:relative;padding:0 0 10mm}section:last-child{page-break-after:auto}header{border-bottom:1px solid #92aa9a;margin:0 0 7mm;padding:2mm 0;font-size:16pt;font-weight:700}footer{position:absolute;bottom:0;left:0;right:0;border-top:1px solid #ccd6d0;padding-top:2mm;font-size:8pt;color:#587463}h1{font-size:29pt;margin:20mm 0 12mm}h2{font-size:15pt;margin-top:10mm}h3{font-size:11pt;margin:0 0 2mm}p{line-height:1.6;margin:3mm 0;overflow-wrap:anywhere}small{display:block;color:#5c7264;font-size:8pt;line-height:1.45;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;font-size:9pt}td,th{border-bottom:1px solid #dbe2dd;padding:2.2mm;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{background:#edf3ef}tr,article,.edge{break-inside:avoid;page-break-inside:avoid}svg{display:block;width:100%;height:auto}article{margin:0 0 6mm}.bom td:first-child{width:61%}.bom small{font-size:8pt}.total{font-size:24pt}.warning{border-left:3px solid #b17b33;padding:3mm;background:#fbf4e8}.kicker{letter-spacing:2px;margin-top:20mm}.right{text-align:right}.url{font-size:8pt;color:#496652}.edge{display:flex;align-items:center;gap:2mm;border-bottom:1px solid #dbe2dd;padding:2mm 0;min-height:19mm}.edge>div{width:42%;border:1px solid #b0c2b6;border-radius:2mm;padding:2mm;font-size:9pt}.edge>span{text-align:center;flex:1}.edge small{font-size:7pt}.issue p{margin:1.5mm 0}</style></head><body>${pages.map((page,i)=>`<section><header>${e(page.title)}</header>${page.body}<footer>组网工坊 0.1.0 · ${e(project.updatedAt.slice(0,10))} · 预算参考 / 现场复核 <span style="float:right">${i+1} / ${pages.length}</span></footer></section>`).join('')}</body></html>`;
}
