import {test,expect} from '@playwright/test';
test('radio prices and optional components change only after apply/join, remove restores amount',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'400㎡ 餐厅',exact:true}).click();await page.getByRole('button',{name:'报价',exact:true}).click();
 const total=page.getByLabel('方案总价'),before=await total.innerText();await page.getByText('可选经营设备',{exact:true}).click();await expect(total).toHaveText(before);
 const pos=page.getByRole('article',{name:'商米 T2s 收银机'});await pos.getByRole('button',{name:'加入方案',exact:true}).click();await expect(total).not.toHaveText(before);await page.getByRole('button',{name:'移除 商米 T2s 收银机',exact:true}).click();await expect(total).toHaveText(before);
 await page.getByRole('button',{name:'平面图',exact:true}).click();await page.getByRole('button',{name:'需求与数量',exact:true}).click();await page.getByLabel('无线代际').selectOption('5');await page.getByRole('button',{name:'应用配置',exact:true}).click();await page.getByRole('button',{name:'报价',exact:true}).click();await expect(total).not.toHaveText(before);await expect(page.getByText('单价均可校正',{exact:false})).toBeVisible();
 const row=page.locator('[data-bom-model]').first();await row.locator('summary').click();await row.getByLabel('采用单价（元）').fill('100');await row.getByRole('button',{name:'应用单价',exact:true}).click();await expect(row.getByLabel('采用单价（元）')).toHaveValue('100');
});
test('a pending price draft cannot be silently discarded by another price or optional purchase',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'400㎡ 餐厅',exact:true}).click();await page.getByRole('button',{name:'报价',exact:true}).click();const lines=page.locator('[data-bom-model]');await lines.nth(0).locator('summary').click();await lines.nth(1).locator('summary').click();await lines.nth(0).getByLabel('采用单价（元）').fill('288');await expect(lines.nth(1).getByLabel('采用单价（元）')).toBeDisabled();await page.getByText('可选经营设备',{exact:true}).click();await expect(page.getByRole('button',{name:'加入方案',exact:true}).first()).toBeDisabled();await lines.nth(0).getByRole('button',{name:'取消单价修改',exact:true}).click();await expect(page.getByRole('button',{name:'加入方案',exact:true}).first()).toBeEnabled();
});
test('an imported fixed-labor quote edits the fixed allowance, not an unused catalog override',async({page})=>{
 await page.goto('/');await page.evaluate(async()=>{const {createScene}=await import('/src/scenes/index.ts');const p=createScene('office');p.settings.laborMode='fixed';p.settings.fixedLaborCents=30000;localStorage.setItem(`netatelier:project:${p.id}`,JSON.stringify(p));localStorage.setItem('netatelier:last',p.id);});await page.reload();await page.getByRole('button',{name:'报价',exact:true}).click();const row=page.locator('[data-bom-model=labor-fixed]');await row.locator('summary').click();await row.getByLabel('采用单价（元）').fill('400');await row.getByRole('button',{name:'应用单价',exact:true}).click();await expect(row.locator('strong')).toHaveText('¥400.00');
});
