import {test,expect} from '@playwright/test';
const draft={width:100,height:100,rooms:[{name:'合成区域',use:'public',polygon:[{x:10,y:10},{x:90,y:10},{x:90,y:90},{x:10,y:90}]}],walls:[],warnings:[]};
test('mismatched original blocks overlay and network while preserving saved draft',async({page})=>{await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;let json:unknown={};const project={id:'p',name:'合成项目',revision:1,data:{draft},originalImage:{id:'im',width:200,height:100,mime:'image/png'}};if(p==='/api/health')json={ok:true,vision:{available:false}};else if(p==='/api/me')json={user:{id:'u',email:'synthetic@example.test'},tenants:[{id:'t',name:'合成团队',role:'owner'}]};else if(p==='/api/members')json={members:[]};else if(p==='/api/projects')json={projects:[project]};else if(p==='/api/projects/p')json={project};else if(p.endsWith('/images/im')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});return}await route.fulfill({json})});await page.goto('/team.html');await page.getByRole('button',{name:'合成项目',exact:true}).click();await expect(page.getByText(/禁止叠加、点选和生成/)).toBeVisible();await expect(page.getByRole('img',{name:'原图校正与组网点位'})).toHaveCount(0);await expect(page.getByRole('button',{name:'生成布点、拓扑与预算'})).toBeDisabled();await expect(page.getByLabel('房间 1 名称')).toHaveValue('合成区域')});

test('image points use SVG coordinates under letterboxing and survive explicit save and reload',async({page})=>{let data:Record<string,unknown>={draft};await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;let json:unknown={};const project=()=>({id:'p',name:'合成项目',revision:1,data,originalImage:{id:'im',width:100,height:100,mime:'image/png'}});if(p==='/api/health')json={ok:true,vision:{available:false}};else if(p==='/api/me')json={user:{id:'u',email:'synthetic@example.test'},tenants:[{id:'t',name:'合成团队',role:'owner'}]};else if(p==='/api/members')json={members:[]};else if(p==='/api/projects')json={projects:[project()]};else if(p==='/api/projects/p'){if(route.request().method()==='PUT')data=route.request().postDataJSON().data;json={project:project()}}else if(p.endsWith('/images/im')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});return}await route.fulfill({json})});await page.goto('/team.html');await page.getByRole('button',{name:'合成项目',exact:true}).click();const svg=page.getByRole('img',{name:'原图校正与组网点位'});await expect(svg).toBeVisible();await svg.evaluate(e=>{(e as SVGElement).style.height='600px';(e as SVGElement).style.width='300px'});await page.getByRole('button',{name:'在原图选择机柜位置',exact:true}).click();await svg.evaluate(e=>{const point=new DOMPoint(30,40).matrixTransform((e as SVGSVGElement).getScreenCTM()!);e.dispatchEvent(new MouseEvent('click',{clientX:point.x,clientY:point.y,bubbles:true}))});await page.getByRole('button',{name:'保存人工校正',exact:true}).click();expect((data.networkInput as any).cabinet.x).toBeCloseTo(30,0);expect((data.networkInput as any).cabinet.y).toBeCloseTo(40,0);await page.reload();await page.getByRole('button',{name:'合成项目',exact:true}).click();await expect(page.getByRole('img',{name:'原图校正与组网点位'}).getByText('机柜',{exact:true})).toBeVisible()});

test('generate and save restores original-image device overlay and budget after reload',async({page})=>{const {buildNetwork}=await import('../../cloud/project-tools');const d={...draft,dimensions:[{value:10,unit:'m',kind:'overall',from:{x:0,y:0},to:{x:100,y:0},evidence:'synthetic horizontal',confidence:1,source:'manual',confirmed:true},{value:10,unit:'m',kind:'overall',from:{x:0,y:0},to:{x:0,y:100},evidence:'synthetic vertical',confidence:1,source:'manual',confirmed:true}]} as Parameters<typeof buildNetwork>[0];const calibration={a:{x:0,y:0},b:{x:100,y:0},lengthM:10,source:'drawing-dimension',evidence:'synthetic horizontal',confirmed:true,canvas:{width:100,height:100},references:d.dimensions} as Parameters<typeof buildNetwork>[1];const networkInput={scene:'office',concurrentUsers:20,wiredPoints:1,confirmedGeometry:true,cabinet:{x:20,y:20},wan:{x:20,y:30}} as Parameters<typeof buildNetwork>[2];const built=buildNetwork(d,calibration,networkInput);let writes=0;let savedData:any={draft:d,calibration,networkInput};await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;const project={id:'p',name:'已保存方案',revision:1,data:savedData,originalImage:{id:'im',width:100,height:100,mime:'image/png'}};let json:unknown={};if(route.request().method()!=='GET')writes++;if(p==='/api/health')json={ok:true,vision:{available:false}};else if(p==='/api/me')json={user:{id:'u',email:'synthetic@example.test'},tenants:[{id:'t',name:'合成团队',role:'owner'}]};else if(p==='/api/members')json={members:[]};else if(p==='/api/projects')json={projects:[project]};else if(p==='/api/projects/p'){if(route.request().method()==='PUT')savedData=route.request().postDataJSON().data;json={project:{...project,data:savedData}}}else if(p.endsWith('/images/im')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});return}await route.fulfill({json})});await page.goto('/team.html');await page.getByRole('button',{name:'已保存方案',exact:true}).click();await page.getByRole('button',{name:'生成布点、拓扑与预算'}).click();await expect(page.getByRole('img',{name:'原图校正与组网点位'}).locator('[data-device-kind=ap]')).toHaveCount(built.project.floors[0].devices.filter(d=>d.kind==='ap').length);await expect(page.getByText(/预算草案 ¥/)).toBeVisible();expect(writes).toBe(0);await page.getByRole('button',{name:'保存人工校正',exact:true}).click();await expect(page.getByRole('status')).toContainText('已保存');expect(savedData.network).toBeTruthy();await page.reload();await page.getByRole('button',{name:'已保存方案',exact:true}).click();await expect(page.getByText(/预算草案 ¥/)).toBeVisible();expect(writes).toBe(1)});

test('removing verified dimension evidence stays invalid after save and reload',async({page})=>{
 const reference=(axis:string)=>({value:10,unit:'m',kind:'reference',from:{x:0,y:0},to:axis==='x'?{x:100,y:0}:{x:0,y:100},evidence:`synthetic ${axis}`,source:'manual',confidence:1,confirmed:true});
 const refs=[reference('x'),reference('y')];let data:any={draft:{...draft,dimensions:refs},calibration:{a:{x:0,y:0},b:{x:100,y:0},lengthM:10,source:'drawing-dimension',evidence:'synthetic ruler',confirmed:true,canvas:{width:100,height:100},references:refs}};
 await page.route('**/api/**',async route=>{const p=new URL(route.request().url()).pathname;const project={id:'p',name:'合成项目',revision:1,data,originalImage:{id:'im',width:100,height:100,mime:'image/png'}};let json:any={};if(p==='/api/health')json={ok:true,vision:{available:false}};else if(p==='/api/me')json={user:{id:'u',email:'synthetic@example.test'},tenants:[{id:'t',name:'合成团队',role:'owner'}]};else if(p==='/api/members')json={members:[]};else if(p==='/api/projects')json={projects:[project]};else if(p==='/api/projects/p'){if(route.request().method()==='PUT')data=route.request().postDataJSON().data;json={project:{...project,data}}}else if(p.endsWith('/images/im')){await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});return}await route.fulfill({json})});
 await page.goto('/team.html');await page.getByRole('button',{name:'合成项目',exact:true}).click();await expect(page.getByLabel('我已核对长度、米单位和对应两点')).toBeChecked();
 await page.getByRole('button',{name:'移除尺寸 2',exact:true}).click();await page.getByRole('button',{name:'保存人工校正',exact:true}).click();expect(data.calibration.confirmed).toBe(false);expect(data.calibration.references).toHaveLength(1);
 await page.reload();await page.getByRole('button',{name:'合成项目',exact:true}).click();await expect(page.getByLabel('我已核对长度、米单位和对应两点')).not.toBeChecked();await expect(page.getByRole('button',{name:'生成布点、拓扑与预算'})).toBeDisabled();
});
