import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { readFile,realpath } from 'node:fs/promises';
import { resolve,sep,extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createStore } from './store.mjs';
import { validateDraft } from './vision.mjs';
import { digestToken,newToken,verifyPassword,normalizeEmail } from './auth.mjs';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const keys=(v,allowed)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k)))fail(400,'Invalid request');};
const name=v=>{if(typeof v!=='string'||!v.trim()||v.length>160)fail(400,'Invalid name');return v.trim();};
const project=row=>({...row,data:JSON.parse(row.data)});
export function assertLoopbackHost(host){if(!['127.0.0.1','::1','localhost'].includes(host))throw new Error('Server host must be loopback');return host;}
export function createApp({dbPath='data/team.sqlite',allowedOrigin='http://localhost:4318',vision,sessionTtlMs=8*3600000,now=Date.now,distPath=resolve('dist-team'),secureCookie=false}={}) {
 const origin=new URL(allowedOrigin);if(!['localhost','127.0.0.1','[::1]'].includes(origin.hostname)||!['http:','https:'].includes(origin.protocol)||origin.origin!==allowedOrigin)throw new Error('Allowed origin must be an exact loopback origin');
 if(!Number.isSafeInteger(sessionTtlMs)||sessionTtlMs<1)throw new Error('Invalid session TTL');
 const store=createStore(dbPath),db=store.db,limits=new Map();let hashing=0;let visionActive=0;const visionUsers=new Set(),visionRates=new Map();
 const cookie=token=>`team_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${token?Math.ceil(sessionTtlMs/1000):0}${secureCookie?'; Secure':''}`;
 async function handler(req,res){
 const send=(status,body,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(body));};
 try {
 const path=new URL(req.url,'http://localhost').pathname,method=req.method;
 if(!path.startsWith('/api/')){if(method!=='GET'&&method!=='HEAD')fail(405,'Method not allowed');const relative=path==='/'?'team.html':decodeURIComponent(path).replace(/^\//,'');if(relative!=='team.html'&&!relative.startsWith('assets/'))fail(404,'Not found');const root=await realpath(distPath).catch(()=>fail(404,'Not found'));const file=await realpath(resolve(root,relative)).catch(()=>fail(404,'Not found'));if(!file.startsWith(root+sep))fail(404,'Not found');const content=await readFile(file);res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'})[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self'; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"});res.end(method==='HEAD'?undefined:content);return;}
 if(path==='/api/health'&&method==='GET'){send(200,{ok:true,mode:'private-loopback'});return;}
 let body;
 if(!['GET','HEAD'].includes(method)){if(req.headers.origin!==allowedOrigin)fail(403,'Invalid origin');if(!/^application\/json(?:\s*;.*)?$/i.test(req.headers['content-type']||''))fail(415,'JSON required');const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>6*1024*1024)fail(413,'Request too large');chunks.push(chunk);}try{body=JSON.parse(Buffer.concat(chunks).toString());}catch{fail(400,'Invalid JSON');}}
 if(path==='/api/login'&&method==='POST'){
 keys(body,['email','password']);let email;try{email=normalizeEmail(body.email);}catch{fail(400,'Invalid email');}if(typeof body.password!=='string'||Buffer.byteLength(body.password)>1024)fail(400,'Invalid password');
 const time=now();for(const [k,v]of limits)if(v.until<=time)limits.delete(k);const key=req.socket.remoteAddress||'local';let limit=limits.get(key);if(!limit){if(limits.size>=1000)limits.delete(limits.keys().next().value);limit={count:0,until:time+60000};limits.set(key,limit);}if(++limit.count>10)fail(429,'Too many attempts');
 if(hashing>=2)fail(429,'Too many attempts');hashing++;let valid=false;const user=db.prepare('SELECT * FROM users WHERE email=?').get(email);try{valid=await verifyPassword(body.password,user?.password_hash||'AAAAAAAAAAAAAAAAAAAAAA==:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=');}finally{hashing--;}if(!user||!valid)fail(401,'Invalid credentials');const token=newToken();db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(time);db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digestToken(token),user.id,time+sessionTtlMs);send(200,{user:{id:user.id,email:user.email}},{'Set-Cookie':cookie(token)});return;
 }
 const raw=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('team_session='))?.slice(13);const session=raw&&db.prepare('SELECT users.id,users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE digest=? AND expires_at>?').get(digestToken(raw),now());if(!session)fail(401,'Authentication required');
 if(path==='/api/logout'&&method==='POST'){keys(body,[]);db.prepare('DELETE FROM sessions WHERE digest=?').run(digestToken(raw));send(200,{ok:true},{'Set-Cookie':cookie('')});return;}
 if(path==='/api/me'&&method==='GET'){send(200,{user:session,tenants:db.prepare('SELECT tenants.id,tenants.name,memberships.role FROM tenants JOIN memberships ON tenants.id=memberships.tenant_id WHERE user_id=? ORDER BY tenants.name').all(session.id)});return;}
 if(path==='/api/tenants'&&method==='POST'){keys(body,['name']);const tenant={id:randomUUID(),name:name(body.name)};db.exec('BEGIN');try{db.prepare('INSERT INTO tenants VALUES(?,?)').run(tenant.id,tenant.name);db.prepare('INSERT INTO memberships VALUES(?,?,?)').run(tenant.id,session.id,'owner');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}send(201,{tenant:{...tenant,role:'owner'}});return;}
 const tenant=req.headers['x-tenant-id'];if(typeof tenant!=='string'||!tenant)fail(400,'Tenant header required');const membership=db.prepare('SELECT role FROM memberships WHERE tenant_id=? AND user_id=?').get(tenant,session.id);if(!membership)fail(403,'Tenant access denied');
 if(path==='/api/members'&&method==='GET'){if(membership.role==='member')fail(403,'Manager required');send(200,{members:db.prepare('SELECT users.id AS userId,users.email,memberships.role FROM memberships JOIN users ON users.id=memberships.user_id WHERE tenant_id=?').all(tenant)});return;}
 if(path==='/api/members'&&method==='POST'){if(membership.role==='member')fail(403,'Manager required');keys(body,['email','role']);if(!['admin','member'].includes(body.role)||(membership.role==='admin'&&body.role!=='member'))fail(403,'Role not permitted');let email;try{email=normalizeEmail(body.email);}catch{fail(400,'Invalid email');}const user=db.prepare('SELECT id,email FROM users WHERE email=?').get(email);if(!user)fail(404,'Account not found');if(db.prepare('SELECT 1 FROM memberships WHERE tenant_id=? AND user_id=?').get(tenant,user.id))fail(409,'Already a member');db.prepare('INSERT INTO memberships VALUES(?,?,?)').run(tenant,user.id,body.role);send(201,{member:{userId:user.id,email:user.email,role:body.role}});return;}
 const memberMatch=path.match(/^\/api\/members\/([^/]+)$/);if(memberMatch&&method==='DELETE'){if(membership.role==='member')fail(403,'Manager required');const target=db.prepare('SELECT role FROM memberships WHERE tenant_id=? AND user_id=?').get(tenant,memberMatch[1]);if(!target)fail(404,'Not found');if(target.role==='owner'&&db.prepare("SELECT count(*) AS n FROM memberships WHERE tenant_id=? AND role='owner'").get(tenant).n<=1)fail(409,'Last owner cannot be removed');if(membership.role==='admin'&&target.role!=='member')fail(403,'Role not permitted');db.prepare('DELETE FROM memberships WHERE tenant_id=? AND user_id=?').run(tenant,memberMatch[1]);send(200,{ok:true});return;}
 if(path==='/api/projects'&&method==='GET'){send(200,{projects:db.prepare('SELECT * FROM projects WHERE tenant_id=? ORDER BY updated_at DESC').all(tenant).map(project)});return;}
 const boundedData=v=>{keys(v,Object.keys(v||{}));if(v.draft!==undefined){try{validateDraft(v.draft);}catch{fail(400,'Invalid draft');}}const encoded=JSON.stringify(v);if(Buffer.byteLength(encoded)>256*1024)fail(413,'Project data too large');return encoded;};
 if(path==='/api/projects'&&method==='POST'){keys(body,['name','data']);const timestamp=new Date(now()).toISOString(),id=randomUUID();db.prepare('INSERT INTO projects VALUES(?,?,?,?,?,?,?)').run(id,tenant,name(body.name),boundedData(body.data??{}),1,timestamp,timestamp);send(201,{project:project(db.prepare('SELECT * FROM projects WHERE id=?').get(id))});return;}
 const match=path.match(/^\/api\/projects\/([^/]+)(?:\/recognitions(?:\/([^/]+))?)?$/);if(!match)fail(404,'Not found');const row=db.prepare('SELECT * FROM projects WHERE id=? AND tenant_id=?').get(match[1],tenant);if(!row)fail(404,'Not found');
 if(path.includes('/recognitions')){if(method==='GET'&&match[2]){const job=db.prepare('SELECT * FROM recognitions WHERE id=? AND project_id=? AND tenant_id=?').get(match[2],row.id,tenant);if(!job)fail(404,'Not found');send(200,{recognition:{id:job.id,status:job.status,draft:JSON.parse(job.draft),confirmed:false}});return;}if(method==='POST'&&!match[2]){keys(body,['mime','imageBase64','consent']);if(!vision)fail(503,'Vision disabled');const visionTime=now();for(const [id,rate]of visionRates)if(rate.until<=visionTime)visionRates.delete(id);if(visionActive>=2||visionUsers.has(session.id))fail(429,'Recognition already busy');let rate=visionRates.get(session.id);if(!rate){if(visionRates.size>=1000)fail(429,'Recognition rate capacity reached');rate={count:0,until:visionTime+60000};visionRates.set(session.id,rate);}if(rate.count>=5)fail(429,'Recognition rate limit reached');rate.count++;visionActive++;visionUsers.add(session.id);let draft;try{draft=validateDraft(await vision.recognize(body));}catch(error){fail(error.status||error.statusCode||503,'Recognition unavailable');}finally{visionActive--;visionUsers.delete(session.id);}if(!db.prepare('SELECT 1 FROM sessions WHERE digest=? AND expires_at>?').get(digestToken(raw),now()))fail(401,'Authentication required');if(!db.prepare('SELECT 1 FROM projects WHERE id=? AND tenant_id=?').get(row.id,tenant)||!db.prepare('SELECT 1 FROM memberships WHERE tenant_id=? AND user_id=?').get(tenant,session.id))fail(404,'Not found');const recognition={id:randomUUID(),status:'draft',draft,confirmed:false};db.prepare('INSERT INTO recognitions VALUES(?,?,?,?,?,?)').run(recognition.id,row.id,tenant,'draft',JSON.stringify(draft),new Date(now()).toISOString());send(201,{recognition});return;}fail(405,'Method not allowed');}
 if(method==='GET'){send(200,{project:project(row)});return;}if(method==='DELETE'){db.prepare('DELETE FROM projects WHERE id=? AND tenant_id=?').run(row.id,tenant);send(200,{ok:true});return;}if(method==='PUT'){keys(body,['name','data','expectedRevision']);if(!Number.isSafeInteger(body.expectedRevision)||body.expectedRevision<1)fail(400,'Invalid revision');const result=db.prepare('UPDATE projects SET name=?,data=?,revision=revision+1,updated_at=? WHERE id=? AND tenant_id=? AND revision=?').run(body.name===undefined?row.name:name(body.name),body.data===undefined?row.data:boundedData(body.data),new Date(now()).toISOString(),row.id,tenant,body.expectedRevision);if(!result.changes)fail(409,'Revision conflict');send(200,{project:project(db.prepare('SELECT * FROM projects WHERE id=?').get(row.id))});return;}fail(405,'Method not allowed');
 }catch(error){if(!res.headersSent)send(error.status||error.statusCode||500,{error:error.status?error.message:'Request failed'});else res.end();}
 }
 const server=http.createServer(handler);server.requestTimeout=35000;server.headersTimeout=10000;const originalListen=server.listen.bind(server);server.listen=(...args)=>{if(typeof args[0]==='object'){assertLoopbackHost(args[0].host||'');}else assertLoopbackHost(typeof args[1]==='string'?args[1]:'');return originalListen(...args);};return {server,store,handler};
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===resolve(process.argv[1])){const {createVisionAdapter}=await import('./vision.mjs');const host=assertLoopbackHost(process.env.TEAM_HOST||'127.0.0.1');const port=Number(process.env.TEAM_PORT||4318);const app=createApp({dbPath:process.env.TEAM_DB_PATH||'data/team.sqlite',allowedOrigin:process.env.TEAM_ALLOWED_ORIGIN||process.env.TEAM_ORIGIN||`http://localhost:${port}`,vision:createVisionAdapter({enabled:process.env.DEEPSEEK_ENABLED==='1',apiKey:process.env.DEEPSEEK_ENABLED==='1'&&process.env.DEEPSEEK_API_KEY_FILE?(await readFile(process.env.DEEPSEEK_API_KEY_FILE,'utf8')).trim():undefined,baseUrl:process.env.DEEPSEEK_BASE_URL,model:process.env.DEEPSEEK_MODEL})});app.server.listen(port,host,()=>console.log(`Team server listening on loopback port ${port}`));}
