import {test,expect} from 'vitest';
import {measuredAreas,buildNetwork,dimensionMeters,dimensionCalibration,dimensionChainMeters,removeDraftRoom,scaleConsistency,metersToDraft} from '../../cloud/project-tools';
const draft={width:100,height:100,rooms:[{name:'办公室',use:'office',polygon:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]}],walls:[],warnings:[]};
const calibration={a:{x:0,y:0},b:{x:100,y:0},lengthM:10,source:'drawing-dimension' as const,evidence:'原图明确标注10m，人工核对',confirmed:true,canvas:{width:100,height:100},references:[{value:10,unit:'m' as const,kind:'overall' as const,from:{x:0,y:0},to:{x:100,y:0},evidence:'horizontal known reference',confidence:1,source:'manual' as const,confirmed:true},{value:10,unit:'m' as const,kind:'reference' as const,from:{x:0,y:0},to:{x:0,y:100},evidence:'vertical independent reference',confidence:1,source:'manual' as const,confirmed:true}]};
test('no square metres are invented without confirmed scale',()=>{expect(measuredAreas(draft,null)).toBeNull();expect(measuredAreas(draft,{...calibration,confirmed:false})).toBeNull();expect(measuredAreas(draft,calibration)?.[0]).toBeCloseTo(100);expect(()=>measuredAreas(draft,{...calibration,lengthM:Infinity})).toThrow()});
test('calibrated draft reuses existing planning routing and budget engines',()=>{const result=buildNetwork(draft,calibration,{scene:'office',concurrentUsers:20,wiredPoints:2,confirmedGeometry:true,cabinet:{x:10,y:10},wan:{x:20,y:10}});expect(result.project.floors).toHaveLength(1);expect(result.project.floors[0].devices.some(d=>d.kind==='ap')).toBe(true);expect(result.derived.bom.length).toBeGreaterThan(0);expect(result.derived.topology.nodes.length).toBeGreaterThan(0);expect(result.derived.issues.some(i=>i.code==='ESTIMATED_PRICES')).toBe(true);expect(()=>buildNetwork(draft,calibration,{scene:'office',concurrentUsers:20,wiredPoints:2,confirmedGeometry:false,cabinet:{x:10,y:10},wan:{x:20,y:10}})).toThrow()});

test('millimetres convert once to metres and calibrated area uses the squared scale',()=>{const dimension={value:10000,unit:'mm' as const,kind:'overall' as const,from:{x:0,y:0},to:{x:100,y:0},evidence:'合成图标注10000mm',confidence:1,source:'manual' as const};expect(dimensionMeters(dimension)).toBe(10);const c=dimensionCalibration(draft,dimension);expect(c.confirmed).toBe(false);expect(measuredAreas(draft,c)).toBeNull();expect(measuredAreas(draft,{...c,confirmed:true})?.[0]).toBe(100);expect(()=>dimensionMeters({...dimension,unit:'unknown'})).toThrow();expect(()=>dimensionCalibration(draft,{...dimension,to:{x:0,y:0}})).toThrow();expect(()=>dimensionCalibration(draft,{...dimension,to:{x:101,y:0}})).toThrow()});

test('elevations cannot calibrate planar geometry and dimension chains preserve millimetre sums',()=>{const base={value:4000,unit:'mm' as const,kind:'chain' as const,from:{x:0,y:0},to:{x:40,y:0},evidence:'synthetic chain',confidence:1,source:'manual' as const,chainId:'top',rawLabel:'4000',confirmed:false};expect(dimensionChainMeters([base,{...base,value:6000,rawLabel:'6000',from:{x:40,y:0},to:{x:100,y:0}}],'top')).toBe(10);expect(()=>dimensionChainMeters([base,base],'top')).toThrow();expect(()=>dimensionCalibration(draft,{...base,kind:'elevation'})).toThrow();expect(()=>dimensionMeters({...base,kind:'elevation'})).toThrow();});

test('one hundred million square millimetres becomes one hundred square metres after explicit calibration',()=>{const mmDraft={...draft,width:10000,height:10000,rooms:[{...draft.rooms[0],polygon:[{x:0,y:0},{x:10000,y:0},{x:10000,y:10000},{x:0,y:10000}]}]};const dimension={value:10000,unit:'mm' as const,kind:'overall' as const,from:{x:0,y:0},to:{x:10000,y:0},evidence:'synthetic mm label',confidence:1,source:'manual' as const};expect(measuredAreas(mmDraft,{...dimensionCalibration(mmDraft,dimension),confirmed:true})?.[0]).toBe(100);});
test('doorway candidates block planning until confirmed and mapped, then retain calibrated opening width',()=>{const opening={from:{x:100,y:40},to:{x:100,y:60},evidence:'synthetic door',confidence:1,confirmed:false,roomIndices:[0]};const config={scene:'office' as const,concurrentUsers:20,wiredPoints:2,confirmedGeometry:true,cabinet:{x:10,y:10},wan:{x:20,y:10}};expect(()=>buildNetwork({...draft,openings:[opening]},calibration,config)).toThrow(/门洞/);const result=buildNetwork({...draft,openings:[{...opening,confirmed:true}]},calibration,config);expect(result.project.floors[0].openings[0].widthM).toBe(2);});
test('a continuous wall across a doorway blocks network generation until geometry is corrected',()=>{const opening={from:{x:100,y:40},to:{x:100,y:60},evidence:'synthetic door',confidence:1,confirmed:true,roomIndices:[0]};expect(()=>buildNetwork({...draft,walls:[{from:{x:100,y:0},to:{x:100,y:100}}],openings:[opening]},calibration,{scene:'office',concurrentUsers:1,wiredPoints:0,confirmedGeometry:true,cabinet:{x:10,y:10},wan:{x:20,y:10}})).toThrow(/墙/)});
test('deleting a room remaps doorway references and withdraws geometry confirmation',()=>{const source={...draft,rooms:[draft.rooms[0],draft.rooms[0],draft.rooms[0]],openings:[{from:{x:1,y:1},to:{x:1,y:2},evidence:'synthetic',confidence:1,confirmed:true,roomIndices:[1,2]}]};const result=removeDraftRoom(source,0);expect(result.rooms).toHaveLength(2);expect(result.openings?.[0].roomIndices).toEqual([0,1]);expect(result.openings?.[0].confirmed).toBe(false);});

test('original drawing pointer coordinates convert into the matching draft frame only',async()=>{const {originalPointerToDraft}=await import('../../cloud/project-tools');expect(originalPointerToDraft({clientX:150,clientY:80},{left:100,top:30,width:100,height:50},{width:200,height:100},{width:200,height:100})).toEqual({x:100,y:100});expect(()=>originalPointerToDraft({clientX:150,clientY:80},{left:100,top:30,width:100,height:50},{width:201,height:100},draft)).toThrow(/坐标框不一致/)});
test('network generation reports missing or unconfirmed scale evidence clearly',()=>{expect(()=>buildNetwork(draft,{...calibration,evidence:'',confirmed:false},{scene:'office',concurrentUsers:20,wiredPoints:2,confirmedGeometry:true,cabinet:{x:10,y:10},wan:{x:20,y:10}})).toThrow(/标尺证据缺失或未确认/)});

test('two independent source-frame references verify scale while a single span cannot generate',()=>{expect(scaleConsistency(draft,calibration).status).toBe('verified');expect(scaleConsistency(draft,{...calibration,references:calibration.references.slice(0,1)}).status).toBe('unverified');expect(()=>buildNetwork(draft,{...calibration,references:[]},{scene:'office',concurrentUsers:1,wiredPoints:0,confirmedGeometry:true,cabinet:{x:10,y:10},wan:{x:20,y:10}})).toThrow(/两条/);expect(scaleConsistency(draft,{...calibration,canvas:{width:101,height:100}}).status).toBe('conflict');});
test('parallel, short, unconfirmed and inconsistent dimensions cannot verify automatic scale',()=>{const refs=calibration.references;expect(scaleConsistency(draft,{...calibration,references:[refs[0],{...refs[1],from:{x:0,y:20},to:{x:100,y:20}}]}).status).toBe('unverified');expect(scaleConsistency(draft,{...calibration,references:[refs[0],{...refs[1],confirmed:false}]}).status).toBe('unverified');expect(scaleConsistency(draft,{...calibration,references:[refs[0],{...refs[1],value:10.15}]}).status).toBe('review');expect(scaleConsistency(draft,{...calibration,references:[refs[0],{...refs[1],value:11}]}).status).toBe('conflict');expect(scaleConsistency(draft,{...calibration,lengthM:12}).status).toBe('conflict');});
test('dimension chains reject gaps, overlaps and noncollinear segments',()=>{const b={value:4,unit:'m' as const,kind:'chain' as const,from:{x:0,y:0},to:{x:40,y:0},evidence:'chain',confidence:1,source:'manual' as const,chainId:'x'};for(const segment of [{from:{x:50,y:0},to:{x:100,y:0}},{from:{x:30,y:0},to:{x:100,y:0}},{from:{x:40,y:0},to:{x:100,y:2}}])expect(()=>dimensionChainMeters([b,{...b,value:6,...segment}],'x')).toThrow();});

test('metric planned points return to original pixel coordinates without adding ruler origin',()=>{expect(metersToDraft(draft,{...calibration,a:{x:20,y:10},b:{x:100,y:10},lengthM:8},{x:5,y:3})).toEqual({x:50,y:30});expect(()=>metersToDraft(draft,calibration,{x:NaN,y:3})).toThrow()});

test('a manual scale bound to another image canvas cannot publish areas or point overlays',()=>{const wrong={...calibration,canvas:{width:101,height:100}};expect(()=>measuredAreas(draft,wrong)).toThrow(/坐标框/);expect(()=>metersToDraft(draft,wrong,{x:1,y:1})).toThrow(/坐标框/);const tiny={...calibration.references[1],to:{x:0,y:5},value:0.5};expect(scaleConsistency(draft,{...calibration,references:[calibration.references[0],tiny]}).status).toBe('unverified');});

test('generation requires explicit infrastructure anchors instead of fabricated room centres',()=>{expect(()=>buildNetwork(draft,calibration,{scene:'office',concurrentUsers:1,wiredPoints:0,confirmedGeometry:true})).toThrow(/机柜与宽带入口/)});
