import {test,expect} from 'vitest';
import {measuredAreas,buildNetwork,dimensionMeters,dimensionCalibration,dimensionChainMeters,removeDraftRoom} from '../../cloud/project-tools';
const draft={width:100,height:100,rooms:[{name:'办公室',use:'office',polygon:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]}],walls:[],warnings:[]};
const calibration={a:{x:0,y:0},b:{x:100,y:0},lengthM:10,source:'drawing-dimension' as const,evidence:'原图明确标注10m，人工核对',confirmed:true};
test('no square metres are invented without confirmed scale',()=>{expect(measuredAreas(draft,null)).toBeNull();expect(measuredAreas(draft,{...calibration,confirmed:false})).toBeNull();expect(measuredAreas(draft,calibration)?.[0]).toBeCloseTo(100);expect(()=>measuredAreas(draft,{...calibration,lengthM:Infinity})).toThrow()});
test('calibrated draft reuses existing planning routing and budget engines',()=>{const result=buildNetwork(draft,calibration,{scene:'office',concurrentUsers:20,wiredPoints:2,confirmedGeometry:true});expect(result.project.floors).toHaveLength(1);expect(result.project.floors[0].devices.some(d=>d.kind==='ap')).toBe(true);expect(result.derived.bom.length).toBeGreaterThan(0);expect(result.derived.topology.nodes.length).toBeGreaterThan(0);expect(result.derived.issues.some(i=>i.code==='ESTIMATED_PRICES')).toBe(true);expect(()=>buildNetwork(draft,calibration,{scene:'office',concurrentUsers:20,wiredPoints:2,confirmedGeometry:false})).toThrow()});

test('millimetres convert once to metres and calibrated area uses the squared scale',()=>{const dimension={value:10000,unit:'mm' as const,kind:'overall' as const,from:{x:0,y:0},to:{x:100,y:0},evidence:'合成图标注10000mm',confidence:1,source:'manual' as const};expect(dimensionMeters(dimension)).toBe(10);const c=dimensionCalibration(draft,dimension);expect(c.confirmed).toBe(false);expect(measuredAreas(draft,c)).toBeNull();expect(measuredAreas(draft,{...c,confirmed:true})?.[0]).toBe(100);expect(()=>dimensionMeters({...dimension,unit:'unknown'})).toThrow();expect(()=>dimensionCalibration(draft,{...dimension,to:{x:0,y:0}})).toThrow();expect(()=>dimensionCalibration(draft,{...dimension,to:{x:101,y:0}})).toThrow()});

test('elevations cannot calibrate planar geometry and dimension chains preserve millimetre sums',()=>{const base={value:4000,unit:'mm' as const,kind:'chain' as const,from:{x:0,y:0},to:{x:40,y:0},evidence:'synthetic chain',confidence:1,source:'manual' as const,chainId:'top',rawLabel:'4000',confirmed:false};expect(dimensionChainMeters([base,{...base,value:6000,rawLabel:'6000',from:{x:40,y:0},to:{x:100,y:0}}],'top')).toBe(10);expect(()=>dimensionChainMeters([base,base],'top')).toThrow();expect(()=>dimensionCalibration(draft,{...base,kind:'elevation'})).toThrow();expect(()=>dimensionMeters({...base,kind:'elevation'})).toThrow();});

test('one hundred million square millimetres becomes one hundred square metres after explicit calibration',()=>{const mmDraft={...draft,width:10000,height:10000,rooms:[{...draft.rooms[0],polygon:[{x:0,y:0},{x:10000,y:0},{x:10000,y:10000},{x:0,y:10000}]}]};const dimension={value:10000,unit:'mm' as const,kind:'overall' as const,from:{x:0,y:0},to:{x:10000,y:0},evidence:'synthetic mm label',confidence:1,source:'manual' as const};expect(measuredAreas(mmDraft,{...dimensionCalibration(mmDraft,dimension),confirmed:true})?.[0]).toBe(100);});
test('doorway candidates block planning until confirmed and mapped, then retain calibrated opening width',()=>{const opening={from:{x:100,y:40},to:{x:100,y:60},evidence:'synthetic door',confidence:1,confirmed:false,roomIndices:[0]};const config={scene:'office' as const,concurrentUsers:20,wiredPoints:2,confirmedGeometry:true};expect(()=>buildNetwork({...draft,openings:[opening]},calibration,config)).toThrow(/门洞/);const result=buildNetwork({...draft,openings:[{...opening,confirmed:true}]},calibration,config);expect(result.project.floors[0].openings[0].widthM).toBe(2);});
test('a continuous wall across a doorway blocks network generation until geometry is corrected',()=>{const opening={from:{x:100,y:40},to:{x:100,y:60},evidence:'synthetic door',confidence:1,confirmed:true,roomIndices:[0]};expect(()=>buildNetwork({...draft,walls:[{from:{x:100,y:0},to:{x:100,y:100}}],openings:[opening]},calibration,{scene:'office',concurrentUsers:1,wiredPoints:0,confirmedGeometry:true})).toThrow(/墙/)});
test('deleting a room remaps doorway references and withdraws geometry confirmation',()=>{const source={...draft,rooms:[draft.rooms[0],draft.rooms[0],draft.rooms[0]],openings:[{from:{x:1,y:1},to:{x:1,y:2},evidence:'synthetic',confidence:1,confirmed:true,roomIndices:[1,2]}]};const result=removeDraftRoom(source,0);expect(result.rooms).toHaveLength(2);expect(result.openings?.[0].roomIndices).toEqual([0,1]);expect(result.openings?.[0].confirmed).toBe(false);});
