import {it,expect} from 'vitest';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {assertReleaseReady,assertApkIdentity,verifyArtifact} from '../../scripts/release.mjs';
function fixture(run:(cwd:string,configPath:string,git:(...a:string[])=>string)=>void){const cwd=mkdtempSync(join(tmpdir(),'netatelier-release-source-')),keys=mkdtempSync(join(tmpdir(),'netatelier-release-test-'));const git=(...a:string[])=>execFileSync('git',['-C',cwd,...a],{encoding:'utf8'});try{git('init','-q');git('config','user.name','Test');git('config','user.email','test@users.noreply.github.com');writeFileSync(join(cwd,'README.md'),'Independent synthetic project');git('add','.');git('commit','-qm','initial');for(const f of ['test.jks','password'])writeFileSync(join(keys,f),'test material',{mode:0o600});const configPath=join(keys,'signing.json');writeFileSync(configPath,JSON.stringify({keystore:join(keys,'test.jks'),alias:'test',storePasswordFile:join(keys,'password'),keyPasswordFile:join(keys,'password')}),{mode:0o600});run(cwd,configPath,git);}finally{rmSync(cwd,{recursive:true,force:true});rmSync(keys,{recursive:true,force:true});}}
it('blocks dirty or untracked source before a release build',()=>fixture((cwd,configPath)=>{writeFileSync(join(cwd,'scratch.txt'),'not committed');expect(()=>assertReleaseReady({cwd,configPath})).toThrow(/clean|dirty/i);}));
it('requires a private external signing configuration',()=>fixture((cwd)=>{expect(()=>assertReleaseReady({cwd,configPath:join(cwd,'missing.json')})).toThrow(/signing|outside|configuration/i);}));
it('rejects tracked signing secrets even after commit',()=>fixture((cwd,configPath,git)=>{writeFileSync(join(cwd,'secret.txt'),'gh'+'p_'+'x'.repeat(36));git('add','.');git('commit','-qm','unsafe');expect(()=>assertReleaseReady({cwd,configPath})).toThrow(/public|credential/i);}));
it('accepts a clean public tree and outside-only private key files',()=>fixture((cwd,configPath,git)=>{expect(assertReleaseReady({cwd,configPath}).commit).toBe(git('rev-parse','HEAD').trim());}));
const expected={packageName:'io.github.rewqasd.netatelier',versionName:'0.1.0',versionCode:1,minSdk:26};
const input={badging:"package: name='io.github.rewqasd.netatelier' versionCode='1' versionName='0.1.0'\nsdkVersion:'26'",permissions:"uses-permission: name='io.github.rewqasd.netatelier.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'",manifestTree:'A: android:allowBackup(0x01010280)=(type 0x12)0x0'};
it('rejects a signed artifact with a different package or version',()=>{expect(()=>assertApkIdentity({...input,badging:input.badging.replace('netatelier','other')},expected)).toThrow(/identity|package/i);expect(()=>assertApkIdentity({...input,badging:input.badging.replace("versionCode='1'","versionCode='2'")},expected)).toThrow(/identity|version/i);});
it('rejects release debugging, backup or network permission',()=>{expect(()=>assertApkIdentity({...input,manifestTree:input.manifestTree+'\n A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff'},expected)).toThrow(/debug/i);expect(()=>assertApkIdentity({...input,permissions:input.permissions+"\nuses-permission: name='android.permission.INTERNET'"},expected)).toThrow(/permission/i);});
it('rejects a downloaded artifact with a mismatching digest',()=>fixture((cwd)=>{expect(()=>verifyArtifact(join(cwd,'README.md'),'0'.repeat(64))).toThrow(/hash|digest/i);}));
it('accepts matching nondebug offline artifact metadata and exact downloaded bytes',()=>fixture((cwd)=>{expect(assertApkIdentity(input,expected)).toMatchObject(expected);writeFileSync(join(cwd,'artifact.bin'),'abc');expect(()=>verifyArtifact(join(cwd,'artifact.bin'),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')).not.toThrow();}));
