import type { Project } from '../../src/domain/model';
import { transformFloor } from '../../src/domain/geometry';
/** Literal independent metric fixture, not generated by a production planner. */
export function minimalProject():Project {
  return {
    schemaVersion: 1, id: 'p-test', name: '校验样例', revision: 0,
    createdAt: '2026-09-26T00:00:00.000Z', updatedAt: '2026-09-26T00:00:00.000Z',
    settings: {
      wifi: 6, bandwidthMbps: 1000, monitoring: true, retentionDays: 30,
      bitrateMbps: 3, cableReserve: 0.1, endpointAllowanceM: 1, dropM: 2,
      portReserve: 0.2, poeReserve: 0.25, cablePurchase: 'box',
      laborMode: 'itemized', fixedLaborCents: 0,
    },
    floors: [{
      id: 'f1', name: '1层', elevationM: 0,
      boundary: [{x:0,y:0},{x:20,y:0},{x:20,y:15},{x:0,y:15}],
      calibration: {kind:'known-length', metersPerPixel:0.05, originPx:{x:0,y:0}, angleRad:0},
      demand: {employees:20, visitors:10, concurrentUsers:20, terminals:30, wiredPoints:4},
      rooms: [{id:'r1',name:'营业区域',use:'public',polygon:[{x:0,y:0},{x:20,y:0},{x:20,y:15},{x:0,y:15}],confirmed:true}],
      walls: [], openings: [], targets: [], devices: [], cables: [],
    }],
    business: [], priceOverrides: {},
  }
}

export function rectangleFloor(){return minimalProject().floors[0];}
export function rotateProject(p:Project,angleRad:number):Project{return {...structuredClone(p),floors:p.floors.map(f=>transformFloor(f,{angleRad,translation:{x:0,y:0}}))};}
export function translateProject(p:Project,x:number,y:number):Project{return {...structuredClone(p),floors:p.floors.map(f=>transformFloor(f,{angleRad:0,translation:{x,y}}))};}
